---
# quality gates to configure Jenkins build pipeline
docs:
  warnings_unhealthy: 68
  warnings_healthy: 34

default:
  ctest_unstable: 0
  warnings_unhealthy: 0
  warnings_healthy: 0

CentOS_6:
  ctest_unstable: 0
  warnings_unhealthy: 42
  warnings_healthy: 21

CentOS_7:
  ctest_unstable: 0
  warnings_unhealthy: 30
  warnings_healthy: 15

CentOS_8:
  ctest_unstable: 0
  warnings_unhealthy: 120
  warnings_healthy: 60

FreeBSD:
  ctest_unstable: 0
  warnings_unhealthy: 25
  warnings_healthy: 12

Debian:
  ctest_unstable: 0
  warnings_unhealthy: 120
  warnings_healthy: 60

Debian_9.0:
  ctest_unstable: 0
  warnings_unhealthy: 80
  warnings_healthy: 40

Fedora:
  ctest_unstable: 0
  warnings_unhealthy: 110
  warnings_healthy: 55

MacOS:
  ctest_unstable: 0
  warnings_unhealthy: 48
  warnings_healthy: 24

openSUSE:
  ctest_unstable: 0
  warnings_unhealthy: 70
  warnings_healthy: 35

RHEL_6:
  ctest_unstable: 0
  warnings_unhealthy: 42
  warnings_healthy: 21

RHEL_7:
  ctest_unstable: 0
  warnings_unhealthy: 30
  warnings_healthy: 15

RHEL_8:
  ctest_unstable: 0
  warnings_unhealthy: 120
  warnings_healthy: 60

SLE:
  ctest_unstable: 0
  warnings_unhealthy: 64
  warnings_healthy: 32

Univention:
  ctest_unstable: 0
  warnings_unhealthy: 68
  warnings_healthy: 34

win:
  ctest_unstable: 0
  warnings_unhealthy: 190
  warnings_healthy: 95

xUbuntu:
  ctest_unstable: 0
  warnings_unhealthy: 70
  warnings_healthy: 35
